# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.env.enable # enable .env support plugin (needed to enable cloud_init support)
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "test"
  config.vm.network "private_network", ip: "192.168.56.10"
  

  # cloud-init script
  config.vm.cloud_init do |cloud_init|
    # With Ubuntu cloud images you have to use cloud_init to get an access
    cloud_init.content_type = "text/cloud-config"
    cloud_init.path = "../scripts/cloud-config.yml"
  end

end
